### ISSUE TITLE
v1 tag does not match v1.0.8 release

### ISSUE THREAD

**Issue by sennyeya** [opticdev/action#35]
Hi! I'm trying to test out Optic and getting an error message that was supposed to be resolved by this PR (#29), `Error: No token was provided. You can generate a token through our app at https://app.useoptic.com/`.

It looks like the `v1` tag is still pointing at the May 3rd release, https://github.com/opticdev/action/releases/tag/v1, not the latest release (v1.0.8), https://github.com/opticdev/action/releases/tag/v1.0.8.

Updating my workflow file from 
```
- uses: opticdev/action@v1
```
to 
```
- uses: opticdev/action@v1.0.8
```
fixes the problem.

Thanks!

**Comment by acunniffe** [comment]
Thanks for reporting this @sennyeya . We didn't have our releases updating the tag properly (now fixed). https://github.com/opticdev/action/tags

Should work now. Anything else we can help with?
